apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swr-cache-proxy.fullname" . }}
  labels:
    {{- include "swr-cache-proxy.labels" . | nindent 4 }}
data:
  ORIGIN_URL: "{{ .Values.swrCacheProxy.originUrl }}"
  CACHE_DIR: "{{ .Values.swrCacheProxy.cacheDir }}"
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
