apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "swr-cache-proxy.fullname" . }}
  labels:
    {{- include "swr-cache-proxy.labels" . | nindent 4 }}
  {{- with .Values.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
{{- if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass }}
{{- end }}
  resources:
    requests:
      storage: {{ mul .Values.env.CACHE_SIZE_LIMIT_HINT 1.2 }} # pvc size is 20% larger than cache size limit
