apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swr-cache-proxy.fullname" . }}
  labels:
    {{- include "swr-cache-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
