name: Lint and test

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - closed
        branches:
            - main
    push:
        branches:
            - main

jobs:
    lint-and-test:
        name: Lint and test
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }}"

            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - name: Install Node.js 18
              uses: actions/setup-node@v2
              with:
                node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Run ESLint
              run: npm run lint

            - name: Build # jest is running against javascript
              run: npm run build

            - name: Test
              run: npm run test

            - name: Upload test results
              uses: actions/upload-artifact@v3
              if: success() || failure()
              with:
                  name: test-results
                  path: junit.xml
